#SPDX-License-Identifier: MIT-0
---
# tasks file for pull_and_push

# pull hello-world
- name: Pull hello-world from Docker Hub
  community.docker.docker_image:
    name: "{{ registry_test_local_image }}"
    source: pull
    force_source: true

# tag
- name: Tag image for local registry
  community.docker.docker_image:
    name: "{{ registry_test_local_image }}"
    repository: "{{ registry_test_remote_image }}"
    source: local
    force_tag: true

# push sul registry

- name: Push image to local registry
  community.docker.docker_image:
    name: "{{ registry_test_remote_image }}"
    source: local
    push: true


# verifica dell'immagine sul registry

- name: Query Registry
  ansible.builtin.uri:
    url: "http://{{ registry_host }}:{{ registry_port }}/v2/_catalog"
    method: GET
    status_code: 200
    return_content: true
  register: registry_catalog

- name: Show Registry 
  ansible.builtin.debug:
    msg: "Catalogo: {{ (registry_catalog.content | from_json).repositories }}"

- name: Query registry tags
  ansible.builtin.uri:
    url: "http://{{ registry_host }}:{{ registry_port }}/v2/{{ registry_test_image }}/tags/list"
    method: GET
    status_code: 200
    return_content: true
  register: registry_tags

- name: Show tags available
  ansible.builtin.debug:
    msg: "Tags per {{ registry_test_image }}: {{ (registry_tags.content | from_json).tags }}"

# pull dal registry
- name: Remove Local Images
  community.docker.docker_image:
    name: "{{ item }}"
    state: absent
    force_absent: true
  loop:
    - "{{ registry_test_local_image }}"
    - "{{ registry_test_remote_image }}"

- name: Pull Image
  community.docker.docker_image:
    name: "{{ registry_test_remote_image }}"
    source: pull
    force_source: true

- name: Test Complete
  ansible.builtin.debug:
    msg: "PUSH and PULL su {{ registry_host }}:{{ registry_port }} FUNZIONANTI"

...