#SPDX-License-Identifier: MIT-0
---
# tasks file for install_docker

- name: Remove Packets 
  ansible.builtin.dnf:
    name: "{{ rm_pack }}"
    state: absent
  when: rm_pack | length > 0

- name: Enable EPEL Repo
  ansible.builtin.dnf:
    name: epel-release
    state: present
  become: true

- name: Docker Repo 
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: "{{ docker_repo }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ docker_key }}"
    state: present

- name: Docker
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    update_cache: true
  notify: Start Docker

- name: Install SDK Python per Docker
  ansible.builtin.dnf:
    name: python3-docker
    state: present

- name:  Docker Service
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started

- name: Wait for Docker socket
  ansible.builtin.wait_for:
    path: /var/run/docker.sock
    state: present
    timeout: 30

- name: Docker Group 
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true

...