registry_port: 5000
registry_host: "192.168.56.11"
registry_test_image: "hello-world"
registry_test_tag: "latest"
registry_test_local_image: "{{ registry_test_image }}:{{ registry_test_tag }}"
registry_test_remote_image: "{{ registry_host }}:{{ registry_port }}/{{ registry_test_image }}:{{ registry_test_tag }}"
registry_test_repo_name: "hello-world"
docker_user: vagrant
rm_pack:
  - podman 
  - buildah 
  - runc 
  - docker 
  - docker-client 
  - docker-client-latest 
  - docker-common 
  - docker-latest 
  - docker-latest-logrotate 
  - docker-logrotate 
  - docker-engine
packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-buildx-plugin 
  - docker-compose-plugin
docker_repo: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
docker_key: "https://download.docker.com/linux/centos/gpg"
container_name: "docker-registry"
storage_dir: "/var/lib/docker-registry"
